MultiShop/Areas/MSAdmin/ViewModels/Color/ColorCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MSAdmin.ViewModels
{
    public class ColorCreateVM
    {
        [Required]
        public string Name { get; set; } = null!;
    }
}

MultiShop/Areas/MSAdmin/ViewModels/Color/ColorUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MSAdmin.ViewModels
{
    public class ColorUpdateVM
    {
        [Required]
        public string Name { get; set; } = null!;
    }
}

MultiShop/Models/Color.cs
using MultiShop.Models.Base;

namespace MultiShop.Models
{
    public class Color:BaseNameableModel
    {
        public ICollection<ProductColor>? ProductColors { get; set; }
    }
}

MultiShop/Areas/MSAdmin/Controllers/ColorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiShop.Areas.MSAdmin.ViewModels;
using MultiShop.DAL;
using MultiShop.Models;

namespace MultiShop.Areas.MSAdmin.Controllers
{
    [Area("MSAdmin")]
    public class ColorController : Controller
    {
        private readonly AppDbContext _context;

        public ColorController(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var colors = await _context.Colors.Where(c=>c.IgnoreQuery==false).Include(c => c.ProductColors).ToListAsync();
            return View(colors);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ColorCreateVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            bool result = _context.Colors.Any(c => c.Name.ToLower().Trim() == vm.Name.ToLower().Trim());
            if (result)
            {
                ModelState.AddModelError("Name", "This Color is already exist");
                return View();
            }
            Color color = new()
            {
                Name = vm.Name
            };
            await _context.Colors.AddAsync(color);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Color color = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (color is null) return NotFound();

            ColorUpdateVM vm = new() { Name = color.Name };

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, ColorUpdateVM colorVM)
        {
            if (!ModelState.IsValid) return View();

            Color existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();
            bool result = _context.Colors.Any(c => c.Name == colorVM.Name && c.Id != id);
            if (result)
            {
                ModelState.AddModelError("Name", "This Color is already exist");
                return View();
            }

            existed.Name = colorVM.Name;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            var existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();
            _context.Colors.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Details(int id)
        {
            if (id <= 0) return BadRequest();
            var color = await _context.Colors
                .Include(c => c.ProductColors)
                .ThenInclude(pc => pc.Product)
                .ThenInclude(p => p.ProductImages).
                FirstOrDefaultAsync(s => s.Id == id);
            if (color == null) return NotFound();

            return View(color);
        }
    }
}

MultiShop/Areas/MSAdmin/Views/Color/Create.cshtml
@model ColorCreateVM


<div class="content-wrapper">
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<form class="forms-sample" method="post" enctype="multipart/form-data">
					<div class="form-group">
						<label asp-for="Name">Name</label>
						<input asp-for="Name" class="form-control" id="Name" placeholder="Name">
						<span class="text-danger" asp-validation-for="Name"></span>
					</div>

					<button type="submit" class="btn btn-primary me-2">Submit</button>
					<a asp-action="Index" class="btn btn-light">Cancel</a>
				</form>
			</div>
		</div>
	</div>
</div>

MultiShop/Areas/MSAdmin/Views/Color/Index.cshtml
@model List<Color>
@{
    int count = 0;
}
<div class="content-wrapper">
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Color</h4>
                <a class="btn btn-success btn-info" asp-controller="Color" asp-action="Create">Create Color</a>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>
                                    No
                                </th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Settings
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (Color color in Model)
                            {
                                count++;
                                <tr>
                                    <td>
                                        @count
                                    </td>
                                    <td>
                                        @color.Name
                                    </td>
                                    <td>
                                        <a asp-action="Update" asp-route-id="@color.Id" class="btn btn-warning btn-info"> <i class="mdi mdi-pencil"></i> Update</a>

                                        @* @if (User.IsInRole("Admin"))
                                    { *@
                                        <a asp-action="Delete" asp-route-id="@color.Id" class="btn btn-danger btn-info"> <i class="mdi mdi-delete"></i> Delete</a>

                                        @* } *@
                                        <a asp-action="Details" asp-route-id="@color.Id" class="btn btn-primary btn-info"> <i class="mdi mdi-open-in-new"></i> Details</a>
                                    </td>
                                </tr>


                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

MultiShop/Areas/MSAdmin/Views/Color/Update.cshtml
@model ColorUpdateVM


<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post" enctype="multipart/form-data">
						<div class="form-group">
							<label asp-for="Name">Name</label>
							<input asp-for="Name" class="form-control" id="Name" placeholder="Name">
							<span class="text-danger" asp-validation-for="Name"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>