MultiShop/Areas/MSAdmin/ViewModels/Slide/SlideCreateVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MSAdmin.ViewModels
{
    public class SlideCreateVM
    {
        [Required]
        [MaxLength(50)]
        public string Title { get; set; }
        public string? Description { get; set; }
        public int Order { get; set; }

        [Required]
        public IFormFile Photo { get; set; }    
    }
}

MultiShop/Areas/MSAdmin/ViewModels/Slide/SlideUpdateVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MSAdmin.ViewModels
{
    public class SlideUpdateVM
    {
        [Required]
        [MaxLength(50,ErrorMessage = "Max length is 50")]
        public string Title { get; set; }
        public string? Description { get; set; }
        public int Order { get; set; }
        public string ImageUrl { get; set; }
        public IFormFile? Photo { get; set; }
    }
}

MultiShop/Models/Slide.cs
using MultiShop.Models.Base;

namespace MultiShop.Models
{
    public class Slide:BaseModel
    {
        public string Title { get; set; } = null!;
        public string? Description { get; set;}
        public string ImageUrl { get; set; } = null!;
        public string ButtonText { get; set; } = "Shop Now";
        public int Order { get; set; }
        public bool IsActive { get; set; }

    }
}

MultiShop/Areas/MSAdmin/Controllers/SlideController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.SqlExpressions;
using MultiShop.Areas.MSAdmin.ViewModels;
using MultiShop.DAL;
using MultiShop.Models;
using MultiShop.Utilities.Extension;

namespace MultiShop.Areas.MSAdmin.Controllers
{
    [Area("MSAdmin")]
    public class SlideController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public SlideController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public async Task<IActionResult> Index()
        {
            List<Slide> slides = await _context.Slides.Where(s=>s.IgnoreQuery==false).ToListAsync();
            return View(slides);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Create(SlideCreateVM vm)
        {
            if (!ModelState.IsValid) return View();

            if (!vm.Photo.ValidateType())
            {
                ModelState.AddModelError("Photo", "Wrong file type");
                return View();
            }

            if (!vm.Photo.ValidateSize(2 * 1024))
            {
                ModelState.AddModelError("Photo", "Size shouldn't be more than 2MB");
            }

            string fileName = await vm.Photo.CreateFile(_env.WebRootPath, "assets", "img");

            Slide exist = await _context.Slides.FirstOrDefaultAsync(s => s.Order == vm.Order);
            if (exist != null)
            {
                int newOrder = _context.Slides.OrderByDescending(s => s.Order).FirstOrDefault().Order;
                exist.Order = newOrder+1;
            }

            Slide slide = new()
            {
                Title = vm.Title,
                Description = vm.Description,
                ImageUrl = fileName,
                Order = vm.Order,
            };

            await _context.Slides.AddAsync(slide);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            Slide? slide = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
            if (slide is null) return NotFound();

            SlideUpdateVM updateSlideVM = new()
            {
                ImageUrl = slide.ImageUrl,
                Title = slide.Title,
                Order = slide.Order,
                Description = slide.Description
            };

            return View(updateSlideVM);
        }


        [HttpPost]
        public async Task<IActionResult> Update(int id, SlideUpdateVM updateSlideVM)
        {
            if (!ModelState.IsValid) return View(updateSlideVM);


            Slide existed = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);
            if (existed is null) return NotFound();


            bool result = _context.Slides.Any(s => s.Title == updateSlideVM.Title &&  s.Id != id);
            if (!result)
            {
                if (updateSlideVM.Photo is not null)
                {
                    if (!updateSlideVM.Photo.ValidateType())
                    {
                        ModelState.AddModelError("Photo", "Wrong file type");
                        return View(updateSlideVM);
                    }
                    if (!updateSlideVM.Photo.ValidateSize(2 * 1024))
                    {
                        ModelState.AddModelError("Photo", "Size shouldn't be more than 2MB");
                        return View(updateSlideVM);
                    }
                    string newImage = await updateSlideVM.Photo.CreateFile(_env.WebRootPath, "assets", "img");
                    existed.ImageUrl.DeleteFile(_env.WebRootPath, "assets", "img");
                    existed.ImageUrl = newImage;

                }

                Slide existOrder = await _context.Slides.FirstOrDefaultAsync(s => s.Order == updateSlideVM.Order);
                if (existOrder != null)
                {
                    existOrder.Order=existed.Order;
                }

                existed.Title = updateSlideVM.Title;
                existed.Description = updateSlideVM.Description;
                existed.Order = updateSlideVM.Order;
                await _context.SaveChangesAsync();
            }
            else
            {
                ModelState.AddModelError("Title", "This Title is already exist");
                return View(existed);
            }


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeletePermanently(int id)
        {
            if (id <= 0) return BadRequest();
            Slide slide = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
            if (slide == null) return NotFound();

            slide.ImageUrl.DeleteFile(_env.WebRootPath, "assets", "img");
            _context.Slides.Remove(slide);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            Slide slide = await _context.Slides.FirstOrDefaultAsync(s => s.Id == id);
            if (slide is null) return NotFound();

            slide.IgnoreQuery = true;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

MultiShop/Areas/MSAdmin/Views/Slide/Create.cshtml
@model SlideCreateVM


<div class="content-wrapper">
	<div class="col-lg-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">
				<form class="forms-sample" method="post" enctype="multipart/form-data">
					<div class="form-group">
						<label asp-for="Photo">Photo</label>
						<input asp-for="Photo" class="form-control" id="Photo" placeholder="Photo">
						<span class="text-danger" asp-validation-for="Photo"></span>
					</div>
					<div class="form-group">
						<label asp-for="Title">Title</label>
						<input asp-for="Title" class="form-control" id="Title" placeholder="Title">
						<span class="text-danger" asp-validation-for="Title"></span>
					</div>
					<div class="form-group">
						<label asp-for="Order">Order</label>
						<input asp-for="Order" class="form-control" id="Order" placeholder="Order">
						<span class="text-danger" asp-validation-for="Order"></span>
					</div>
					<div class="form-group">
						<label asp-for="Description">Description</label>
						<input asp-for="Description" class="form-control" id="name" placeholder="Description">
						<span class="text-danger" asp-validation-for="Description"></span>
					</div>

					<button type="submit" class="btn btn-primary me-2">Submit</button>
					<a asp-action="Index" class="btn btn-light">Cancel</a>
				</form>
			</div>
		</div>
	</div>
</div>

MultiShop/Areas/MSAdmin/Views/Slide/Index.cshtml
@model List<Slide>
@{
    int count = 0;
}
    <div class="content-wrapper">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Slides</h4>
                    <a class="btn btn-success btn-info" asp-controller="Slide" asp-action="Create">Create Slide</a>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        No
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Title
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th>
                                        Order
                                    </th>
                                    <th>
                                        Settings
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (Slide slide in Model)
                                {
                                    count++;
                                    <tr>
                                        <td>
                                            @count
                                        </td>
                                        <td>
                                            <img style="width:300px; height:150px;" src="~/assets/img/@slide.ImageUrl" />
                                        </td>
                                        <td>
                                           @slide.Title
                                        </td>
                                        <td>
                                            @slide.Description
                                        </td>
                                        <td>
                                            @slide.Order
                                        </td>
                                        <td>
                                            <a asp-action="Update" asp-route-id="@slide.Id" class="btn btn-warning btn-info"> <i class="mdi mdi-pencil"></i> Update</a>
                                            
                                            @* @if (User.IsInRole("Admin"))
                                            { *@
                                            <a asp-action="Delete" asp-route-id="@slide.Id" class="btn btn-danger btn-info"> <i class="mdi mdi-delete"></i> Delete</a>
                                                
                                            @* } *@
                                            <a asp-action="Details" asp-route-id="@slide.Id" class="btn btn-primary btn-info"> <i class="mdi mdi-open-in-new"></i> Details</a>
                                        </td>
                                    </tr>


                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

MultiShop/Areas/MSAdmin/Views/Slide/Update.cshtml
@model SlideUpdateVM


<div class="content-wrapper">
	<div class="row">
		<div class="col-lg-12 grid-margin stretch-card">
			<div class="card">
				<div class="card-body">
					<form class="forms-sample" method="post" enctype="multipart/form-data">
						<div class="form-group">
							<img src="~/assets/img/@Model.ImageUrl" />
							<input asp-for="ImageUrl" class="form-control">
						</div>
						<div class="form-group">
							<label asp-for="Photo">Choose new photo</label>
							<input asp-for="Photo" class="form-control" id="Photo" placeholder="Photo">
							<span class="text-danger" asp-validation-for="Photo"></span>
						</div>
						<div class="form-group">
							<label asp-for="Title">Title</label>
							<input asp-for="Title" class="form-control" id="Title" placeholder="Title">
							<span class="text-danger" asp-validation-for="Title"></span>
						</div>
						<div class="form-group">
							<label asp-for="Order">Order</label>
							<input asp-for="Order" class="form-control" id="Order" placeholder="Order">
							<span class="text-danger" asp-validation-for="Order"></span>
						</div>
						<div class="form-group">
							<label asp-for="Description">Description</label>
							<input asp-for="Description" class="form-control" id="name" placeholder="Description">
							<span class="text-danger" asp-validation-for="Description"></span>
						</div>

						<button type="submit" class="btn btn-primary me-2">Submit</button>
						<a asp-action="Index" class="btn btn-light">Cancel</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>